.TH A2WCRECALC\-DMS 1 "2026-07-05" "a2tools 1.0.0" "User Commands"
.SH NAME
a2wcrecalc\-dms \- \fBa2wcrecalc\fR plus \fBdocker\-mailserver\fR mapping files
.SH SYNOPSIS
.B a2wcrecalc\-dms
.RI [ wildcard\-domain ]
.SH DESCRIPTION
\fBa2wcrecalc\-dms\fR behaves exactly like \fBa2wcrecalc\fR(1) and then
additionally generates the per\-domain mapping files used by
\fBdocker\-mailserver\fR (\fBhttps://github.com/docker\-mailserver/docker\-mailserver\fR)
to discover which virtual host each incoming connection should be
routed to.
.PP
The \fBDMS_DIR\fR environment variable points to the
\fBdocker\-mailserver\fR mount directory. If unset, it defaults to
\fB/opt/compose/docker\-mailserver\fR.
.SH ENVIRONMENT
.TP
.B DMS_DIR
Path to the \fBdocker\-mailserver\fR mount directory.
.SH SEE ALSO
.BR a2wcrecalc (1),
.BR a2sitemgr (1)
